name: Build Chromium iOS IPA

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0'

env:
  SCCACHE_DIR: ${{ github.workspace }}/sccache
  SCCACHE_CACHE_SIZE: 8G

jobs:
  build:
    runs-on: macos-14-large   # 150 GB SSD
    steps:
      # 0. 取当前日期做 key
      - name: Compute cache key
        id: cache_key
        run: echo "date=$(date -u +%Y-%m-%d)" >> $GITHUB_OUTPUT

      # 1. 缓存 depot_tools
      - name: Cache depot_tools
        uses: actions/cache@v4
        with:
          path: ~/depot_tools
          key: depot_tools-${{ runner.os }}-20240601

      # 2. 缓存源码
      - name: Cache chromium src
        uses: actions/cache@v4
        with:
          path: chromium
          key: chromium-src-${{ steps.cache_key.outputs.date }}
          restore-keys: chromium-src-

      # 3. 缓存 sccache
      - name: Cache sccache
        uses: actions/cache@v4
        with:
          path: ${{ env.SCCACHE_DIR }}
          key: sccache-${{ runner.os }}-${{ steps.cache_key.outputs.date }}

      # 4. 安装工具
      - name: Setup depot_tools
        run: |
          if [ ! -d ~/depot_tools ]; then
            git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git ~/depot_tools
          fi
          echo "$HOME/depot_tools" >> $GITHUB_PATH

      - name: Install sccache
        run: brew install sccache

      # 5. 拉源码（仅缓存 miss）
      - name: Fetch Chromium
        if: steps.cache-chromium.outputs.cache-hit != 'true'
        run: |
          mkdir chromium && cd chromium
          fetch --nohooks --no-history ios
          gclient sync --nohooks --no-history

      # 6. 官方一键 GN + 编译
      - name: Setup GN
        run: |
          cd chromium/src
          ios/build/tools/setup-gn.py --target-device ios --configuration release

      - name: Ninja build
        run: |
          cd chromium/src
          autoninja -C out/Release-iphoneos ios_chrome

      # 7. 打包 & 上传
      - name: Package IPA
        run: |
          cd chromium/src/out/Release-iphoneos
          mkdir -p Payload
          cp -R ios_chrome.app Payload/
          zip -r chromium-ios-unsigned.ipa Payload

      - uses: actions/upload-artifact@v4
        with:
          name: ipa
          path: chromium/src/out/Release-iphoneos/chromium-ios-unsigned.ipa
