name: Build Chromium iOS IPA (with sccache)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0'   # 每周日凌晨 2 点跑一次

env:
  # 让 depot_tools 也走 sccache
  GYP_GENERATORS: ninja
  CC_WRAPPER: sccache
  # 配置 sccache 缓存目录、日志
  SCCACHE_DIR: ${{ github.workspace }}/sccache
  SCCACHE_CACHE_SIZE: 5G
  SCCACHE_LOG: debug
  # 让 gn 检测到 sccache
  GN_EXTRA_ARGS: 'cc_wrapper="sccache"'

jobs:
  build:
    runs-on: macos-14

    steps:
      # 1. 取源码缓存 key
      - name: Compute cache key
        id: cache_key
        run: echo "key=chromium-ios-$(date -u +%Y-%m-%d)" >> $GITHUB_OUTPUT

      # 2. 恢复 sccache
      - name: Cache sccache
        uses: actions/cache@v4
        with:
          path: ${{ env.SCCACHE_DIR }}
          key: sccache-${{ runner.os }}-${{ steps.cache_key.outputs.key }}
          restore-keys: |
            sccache-${{ runner.os }}-

      # 3. 准备 depot_tools
      - name: Checkout builder repo
        uses: actions/checkout@v4

      - name: Setup depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$PWD/depot_tools" >> $GITHUB_PATH

      # 4. 安装 sccache
      - name: Install sccache
        run: |
          brew install sccache
          sccache --version

      # 5. 拉取源码（浅克隆）
      - name: Fetch Chromium
        run: |
          mkdir chromium && cd chromium
          fetch --nohooks --no-history ios
          gclient sync --nohooks --no-history

      # 6. 生成构建配置（带 sccache）
      - name: Generate build files
        run: |
          cd chromium/src
          gn gen out/ios_Release \
            --args='target_os="ios" is_debug=false enable_ios_bitcode=false treat_warnings_as_errors=false ${{ env.GN_EXTRA_ARGS }}'

      # 7. 真正开始编译
      - name: Ninja build
        run: |
          cd chromium/src
          autoninja -C out/ios_Release ios_chrome

      # 8. 打包
      - name: Create unsigned IPA
        run: |
          cd chromium/src/out/ios_Release
          mkdir -p Payload
          cp -R ios_chrome.app Payload/
          zip -r chromium-ios-unsigned.ipa Payload

      # 9. 上传产物
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: chromium-ios-unsigned
          path: chromium/src/out/ios_Release/chromium-ios-unsigned.ipa

      # 10. 打印 sccache 命中率（可选）
      - name: sccache stats
        run: sccache --show-stats